
import { SiteText } from "@/components/common/SiteText";
import Link from "next/link";
import { buildMetadata } from "@/lib/seo";
import styles from "./subscriptions.module.css";

export const metadata = buildMetadata({ title: "Círculo MAI · Un espacio para profundizar", description: "Conoce la propuesta de estudio quincenal con Melina: belleza, cosmética y autoformulación. Inscripciones en preparación; empieza por un encuentro personal.", path: "/subscriptions" });

export default function SubscriptionsPage() {
  return <div className={styles.page}>
    <section className={styles.hero}>
      <div><p className="eyebrow"><SiteText id="c662999905f0f1ce3665">{"CÍRCULO MAI · EN PREPARACIÓN"}</SiteText></p><h1><SiteText id="73a9b477c56365734cdf">{"Hay preguntas"}</SiteText><br /><SiteText id="56ba67bcb1bbfc682d00">{"que merecen"}</SiteText><br /><em><SiteText id="353cdf3dbdff2577339a">{"más de un encuentro."}</SiteText></em></h1><p><SiteText id="5677800df2e0ae5fc8c9">{"Lo que empieza con una conversación puede convertirse en una nueva manera de mirarte. Un espacio para estudiar, compartir y darle continuidad a tus preguntas junto a Melina."}</SiteText></p><Link className="mai-button" href="/services#tu-encuentro"><SiteText id="8752d452fb10cec67812">{"Empezar por mi encuentro ↗"}</SiteText></Link><a className={styles.secondary} href="#el-circulo"><SiteText id="a2c5abe42ed5a82b4056">{"Descubrir el Círculo ↓"}</SiteText></a><small><SiteText id="90369d0f213828f26fce">{"El encuentro inicial es independiente. No te suscribe ni activa cobros recurrentes."}</SiteText></small></div>
      <div className={styles.art}><div aria-hidden="true">✳</div><p><SiteText id="57be1d83b2285588980b">{"Escuchar."}</SiteText><br /><SiteText id="88fffe1d2598e69fa908">{"Preguntar."}</SiteText><br /><em><SiteText id="1845b53705f2f9cc94a2">{"Volver a ti."}</SiteText></em></p><span><SiteText id="24e622e1cb2f3a01512c">{"UNA EXPLORACIÓN COMPARTIDA"}</SiteText></span></div>
    </section>
    <section id="el-circulo" className={styles.details}><p className="eyebrow"><SiteText id="729f112daa70b7f45528">{"LA PROPUESTA QUE ESTAMOS PREPARANDO"}</SiteText></p><h2><SiteText id="2aac7de852b6ad52e07d">{"El cuidado como"}</SiteText><br /><em><SiteText id="0505d5a760c00ef4b744">{"punto de partida."}</SiteText></em></h2><div className={styles.grid}>
      <article><span><SiteText id="e4ab916c03a084b1eb27">{"01 / EL RITMO"}</SiteText></span><h3><SiteText id="e5ec1ec8ad905212b4cc">{"Encontrarnos cada quince días"}</SiteText></h3><p><SiteText id="45f4df35e84a31d2157f">{"Grupos de estudio quincenales para dar espacio a las preguntas y volver a ellas con nuevas perspectivas."}</SiteText></p></article>
      <article><span><SiteText id="ed2fd703acb9792326f0">{"02 / LA MIRADA"}</SiteText></span><h3><SiteText id="29cc1bfcee50edc96e49">{"Belleza y algo más"}</SiteText></h3><p><SiteText id="13c3a0fa80f01c2daaa4">{"Cosmética, hábitos y autoformulación: explorar cómo te nombras, qué eliges y cómo participas en tu propia realidad."}</SiteText></p></article>
      <article><span><SiteText id="7ece2c27ffa3d2c1da58">{"03 / TU DECISIÓN"}</SiteText></span><h3><SiteText id="c301ce30bf392205540b">{"Continuar con intención"}</SiteText></h3><p><SiteText id="0e0fff1d7ba0896f7db3">{"Conocer el enfoque de Melina en un encuentro personal y decidir después si quieres profundizar en grupo."}</SiteText></p></article>
    </div></section>
    <section className={styles.invitation}><div><p className="eyebrow"><SiteText id="c8f735e9fe6130afcfb4">{"A TU RITMO"}</SiteText></p><h2><SiteText id="742d1951d76753cd0bde">{"Primero, una conversación."}</SiteText><br /><em><SiteText id="a5d5ce2041a5ebe12cb0">{"El siguiente paso lo eliges tú."}</SiteText></em></h2><p><SiteText id="63467d111866222f024c">{"Melina Jimenez Isaza, creadora de MAI, acompaña este recorrido desde su experiencia cosmética y su mirada de exploración personal."}</SiteText></p></div><div className={styles.status}><strong><SiteText id="278be896b91b13b0d547">{"Inscripciones aún no abiertas"}</SiteText></strong><p><SiteText id="fe49a762c4fc85fba27a">{"Publicaremos precio, modalidad, calendario y condiciones de renovación y cancelación antes de ofrecer una membresía. Hoy no se reciben pagos ni altas al Círculo."}</SiteText></p><Link href="/services#tu-encuentro" className="mai-button"><SiteText id="6f4f04687497f6ffff8e">{"Conocer mi primer encuentro ↗"}</SiteText></Link><Link href="/blog" className={styles.secondary}><SiteText id="8afe9d8037ce00682aa0">{"Mientras tanto, explorar el Diario MAI →"}</SiteText></Link></div></section>
    <section className={styles.faq}><h2><SiteText id="c5dd2a85eecb908585aa">{"Antes de dar"}</SiteText><br /><em><SiteText id="cd51c5b5af9d4492a104">{"el siguiente paso."}</SiteText></em></h2><div>{[
      ["¿Ya puedo suscribirme?", "Aún no. Estamos preparando la propuesta y sus condiciones. No hay planes disponibles para contratar ni cobros de membresía habilitados."],
      ["¿El encuentro con Melina me inscribe?", "No. Es una asesoría individual con su propio valor y alcance, visibles antes de solicitarla. Si te interesa la continuidad puedes conversarlo con Melina, sin compromiso de suscripción."],
      ["¿Incluye productos o descuentos?", "No hay beneficios comerciales confirmados para el Círculo. Los productos y las asesorías se consultan por separado; no necesitas comprar una membresía para acceder al catálogo."],
      ["¿Cómo podré renovar o cancelar?", "Las condiciones y el mecanismo de cancelación se comunicarán antes de abrir inscripciones. Esta página no crea una membresía ni autoriza renovaciones."],
      ["¿Qué tipo de acompañamiento propone?", "Estudio sobre belleza, cosmética y exploración personal. No sustituye atención médica ni psicoterapia. Puedes conocer el enfoque de Melina en la página de Asesorías."],
    ].map(([question,answer], faqIndex) => <details key={question}><summary><SiteText id={`subscriptions:faq:${faqIndex}:question`}>{question}</SiteText></summary><p><SiteText id={`subscriptions:faq:${faqIndex}:answer`}>{answer}</SiteText></p></details>)}</div></section>
  </div>;
}
