'use client';
import Image from 'next/image';
import {useEffect,useState,useTransition} from 'react';
import {saveBlogPost} from '@/app/admin/blog/actions';
import {blogEditorSchema,readingTime,type BlogDraft} from '@/lib/blog-editor';
import ProductImageUploader from './ProductImageUploader';
import BlogMediaEditor from './BlogMediaEditor';
import BlogMedia from '@/components/features/blog/BlogMedia';
const empty=():BlogDraft=>({slug:'',title:'',description:'',category:'Cuidado botánico',publishedAt:new Date().toISOString(),heroImage:'',heroAlt:'',keywords:[],status:'draft',revision:0,sections:[{heading:'',body:['']}],relatedProductCategory:'facial'});
const slugify=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,160);
const inputClass='mt-2 block w-full rounded-lg border border-slate-300 bg-white p-3 text-base';
export default function BlogEditor({initialPosts}:{initialPosts:BlogDraft[]}){
 const [posts,setPosts]=useState(initialPosts),[draft,setDraft]=useState<BlogDraft|null>(null),[original,setOriginal]=useState<string|null>(null),[baseline,setBaseline]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState(false),[uploading,setUploading]=useState(false),[pending,start]=useTransition(),[query,setQuery]=useState('');
 const dirty=!!draft&&JSON.stringify(draft)!==baseline;
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const open=(post?:BlogDraft)=>{const next=post?structuredClone(post):empty();setDraft(next);setOriginal(post?.slug??null);setBaseline(JSON.stringify(next));setPreview(false);setMessage('');};
 const change=<K extends keyof BlogDraft>(key:K,value:BlogDraft[K])=>setDraft(current=>current?{...current,[key]:value}:null);
 const save=(status:BlogDraft['status'])=>{
  if(!draft||pending||uploading)return;
  const next={...draft,status,publishedAt:status==='published'&&draft.status!=='published'?new Date().toISOString():draft.publishedAt};
  const parsed=blogEditorSchema.safeParse(next);if(!parsed.success){setMessage(parsed.error.issues.map(e=>e.message).join(' · '));return;}
  if(status==='scheduled'&&Date.parse(next.publishedAt)<=Date.now()){setMessage('Elige una fecha futura para programar el artículo.');return;}
  start(async()=>{try{const result=await saveBlogPost(parsed.data,original);if(result.error){setMessage(result.error);return;}const saved=result.post!;setPosts(all=>[saved,...all.filter(p=>p.slug!==saved.slug)]);setDraft(saved);setOriginal(saved.slug);setBaseline(JSON.stringify(saved));setMessage(status==='draft'?'Borrador guardado. No es visible en el sitio.':status==='scheduled'?'Artículo programado.':'Artículo publicado.');}catch(error){setMessage(error instanceof Error?error.message:'No se pudo guardar. Tus cambios siguen aquí.');}});
 };
 if(!draft)return <section className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Blogs · Diario MAI</h1><p className="mt-2 text-slate-600">Escribe historias completas, revisa su vista previa y decide cuándo publicarlas.</p></div><button onClick={()=>open()} className="rounded-full bg-brand-700 px-6 py-3 text-white">+ Crear blog</button></header><label className="block">Buscar artículo<input className={inputClass} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Título o categoría"/></label><div className="grid gap-4 md:grid-cols-2">{posts.filter(p=>(p.title+' '+p.category).toLowerCase().includes(query.toLowerCase())).map(post=><article key={post.slug} className="overflow-hidden rounded-2xl border bg-white p-5">{post.heroImage&&<Image src={post.heroImage} alt={post.heroAlt||post.title} width={640} height={360} className="mb-4 aspect-video w-full rounded-xl object-cover"/>}<p className="text-sm text-brand-700">{post.status==='draft'?'Borrador':Date.parse(post.publishedAt)>Date.now()?'Programado':'Publicado'} · {post.category}</p><h2 className="mt-2 text-xl font-bold">{post.title}</h2><p className="mt-2 line-clamp-2 text-slate-600">{post.description}</p><button onClick={()=>open(post)} className="mt-4 rounded-full border px-4 py-2">Editar artículo</button></article>)}</div>{!posts.some(p=>(p.title+' '+p.category).toLowerCase().includes(query.toLowerCase()))&&<p className="rounded-xl border bg-white p-6">{posts.length?'No hay blogs que coincidan con tu búsqueda.':'Todavía no hay blogs. Crea el primero con el botón Crear blog.'}</p>}</section>;
 return <section className="space-y-6"><header className="lg:sticky lg:top-0 z-10 rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><button disabled={pending||uploading} onClick={()=>{if(!dirty||window.confirm('¿Descartar los cambios sin guardar?'))setDraft(null);}}>← Artículos</button><span className="text-sm">{dirty?'Cambios sin guardar':'Guardado'} · {readingTime(draft.sections)} de lectura</span></div><h1 className="my-3 text-2xl font-bold">{original?'Editar artículo':'Crear artículo'}</h1><div className="flex flex-wrap gap-2"><button disabled={pending||uploading} onClick={()=>setPreview(!preview)} aria-pressed={preview} className="rounded-full border px-4 py-2">{preview?'Volver a escribir':'Vista previa'}</button><button disabled={pending||uploading} onClick={()=>save('draft')} className="rounded-full border px-4 py-2">{draft.status==='published'?'Retirar y guardar como borrador':'Guardar borrador'}</button><button disabled={pending||uploading} onClick={()=>save('published')} className="rounded-full bg-brand-700 px-4 py-2 text-white">{pending?'Guardando…':'Publicar ahora'}</button><button disabled={pending||uploading} onClick={()=>save('scheduled')} className="rounded-full border px-4 py-2">Programar</button></div>{message&&<p role="status" className="mt-3 rounded bg-brand-50 p-3">{message}</p>}</header>
 {preview?<article className="mx-auto max-w-3xl space-y-6 rounded-2xl bg-white p-6"><p className="text-sm text-slate-500">Vista previa local · aún no publica los cambios</p><p>{draft.category}</p><h1 className="text-4xl font-bold">{draft.title||'Título del artículo'}</h1><p className="text-lg">{draft.description}</p>{draft.heroImage&&<Image src={draft.heroImage} alt={draft.heroAlt} width={960} height={540} className="aspect-video w-full rounded-xl object-cover"/>}{draft.sections.map((section,i)=><section key={i} className="space-y-3"><h2 className="text-2xl font-bold">{section.heading}</h2>{section.body.map((p,j)=><p key={j} className="whitespace-pre-wrap leading-7">{p}</p>)}<BlogMedia images={section.media} layout={section.layout} label={section.heading}/></section>)}</article>:<fieldset disabled={pending||uploading} className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(250px,1fr)]"><div className="space-y-6"><section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">1. Presentación</h2><label className="block">Título del artículo<input maxLength={180} className={inputClass} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value,...(!original&&(!draft.slug||draft.slug===slugify(draft.title))?{slug:slugify(e.target.value)}:{})})}/></label><label className="block">Resumen · aparece en las tarjetas y buscadores<textarea rows={3} maxLength={500} className={inputClass} value={draft.description} onChange={e=>change('description',e.target.value)}/><small>{draft.description.length} caracteres. Resume qué encontrará quien lo lea.</small></label></section>
 <section className="space-y-5 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">2. Cuerpo del artículo</h2><p className="text-sm text-slate-600">Organiza la historia con subtítulos. Separa párrafos con una línea en blanco; no necesitas HTML.</p>{draft.sections.map((section,i)=><fieldset key={i} className="space-y-3 rounded-xl border p-4"><legend className="px-2 font-semibold">Sección {i+1}</legend><label className="block">Subtítulo<input className={inputClass} value={section.heading} onChange={e=>change('sections',draft.sections.map((s,j)=>j===i?{...s,heading:e.target.value}:s))}/></label><label className="block">Párrafos<textarea rows={8} className={inputClass} value={section.body.join('\n\n')} onChange={e=>change('sections',draft.sections.map((s,j)=>j===i?{...s,body:e.target.value.split('\n\n')}:s))}/></label><BlogMediaEditor section={section} category={draft.relatedProductCategory||'facial'} onChange={next=>setDraft(current=>current?{...current,sections:current.sections.map((s,j)=>j===i?next:s)}:current)} onBusy={setUploading}/><div className="flex flex-wrap gap-2"><button disabled={i===0} type="button" onClick={()=>{const next=[...draft.sections];[next[i-1],next[i]]=[next[i],next[i-1]];change('sections',next);}}>↑ Subir sección {i+1}</button><button disabled={i===draft.sections.length-1} type="button" onClick={()=>{const next=[...draft.sections];[next[i+1],next[i]]=[next[i],next[i+1]];change('sections',next);}}>↓ Bajar sección {i+1}</button><button type="button" onClick={()=>{if(window.confirm('¿Quitar esta sección?'))change('sections',draft.sections.filter((_,j)=>j!==i));}}>Quitar sección {i+1}</button></div></fieldset>)}<button disabled={draft.sections.length>=40} type="button" className="rounded-full border px-4 py-2" onClick={()=>change('sections',[...draft.sections,{heading:'',body:['']}])}>+ Agregar sección</button></section></div>
 <aside className="space-y-6"><section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">3. Portada y accesibilidad</h2>{draft.heroImage&&<Image src={draft.heroImage} alt={draft.heroAlt||'Portada seleccionada'} width={500} height={300} className="aspect-video w-full rounded object-cover"/>}<ProductImageUploader successMessage="Subida. Guarda el artículo para publicarla." category={draft.relatedProductCategory||'facial'} remaining={1} onUploaded={url=>change('heroImage',url)} onBusy={setUploading}/><details><summary>Usar una imagen existente</summary><label className="block">URL de la portada<input className={inputClass} value={draft.heroImage} onChange={e=>change('heroImage',e.target.value)}/></label></details><label className="block">Descripción de la imagen (texto alternativo)<textarea rows={2} className={inputClass} value={draft.heroAlt} onChange={e=>change('heroAlt',e.target.value)} placeholder="Describe lo que se ve en la portada"/></label></section>
 <section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">4. Organización y publicación</h2><label className="block">Categoría editorial<input className={inputClass} value={draft.category} onChange={e=>change('category',e.target.value)}/></label><label className="block">Dirección del artículo<input disabled={!!original} className={inputClass} value={draft.slug} onChange={e=>change('slug',slugify(e.target.value))}/><small>/blog/{draft.slug||'titulo-del-articulo'}</small></label><label className="block">Temas (separados por comas)<input className={inputClass} value={draft.keywords.join(', ')} onChange={e=>change('keywords',e.target.value.split(',').map(s=>s.trim()))}/></label><label className="block">Productos relacionados<select className={inputClass} value={draft.relatedProductCategory||''} onChange={e=>change('relatedProductCategory',(e.target.value||undefined) as BlogDraft['relatedProductCategory'])}><option value="">Sin categoría</option>{['facial','capilar','corporal','kits'].map(c=><option key={c} value={c}>{c}</option>)}</select></label><label className="block">Fecha para programar (hora de este computador)<input type="datetime-local" className={inputClass} value={new Date(Date.parse(draft.publishedAt)-new Date(draft.publishedAt).getTimezoneOffset()*60000).toISOString().slice(0,16)} onChange={e=>{if(e.target.value)change('publishedAt',new Date(e.target.value).toISOString());}}/></label><p className="text-sm">Guardar borrador no publica. Publicar ahora lo muestra en Diario MAI. Programar lo mantiene oculto hasta la fecha elegida.</p></section></aside></fieldset>}</section>;
}
