'use client';
import {useEffect,useState,useTransition} from 'react';
import Link from 'next/link';
import {saveSiteContent} from '@/app/admin/content/actions';
import {contentBlocks,contentLocation} from '@/lib/content-layout';
type Entry={key:string;source:string;text:string;value:string;revision:number};
export default function ContentEditor({entries}:{entries:Entry[]}){
 const [values,setValues]=useState(entries),[source,setSource]=useState<string|null>(null),[draft,setDraft]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[pending,start]=useTransition(),[preview,setPreview]=useState(false),[query,setQuery]=useState('');
 const byKey=Object.fromEntries(values.map(e=>[e.key,e]));
 const blocks=contentBlocks.filter(block=>block.keys.every(key=>byKey[key]));
 const sources=[...new Set(blocks.map(block=>block.source))];
 const active=blocks.filter(block=>block.source===source);
 const text=(block:typeof blocks[number])=>block.keys.map(key=>byKey[key].value).filter(Boolean).join(' ').replace(/\s+/g,' ').trim();
 const changed=active.filter(block=>draft[block.id]!==undefined&&draft[block.id]!==text(block));
 useEffect(()=>{if(!changed.length)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[changed.length]);
 const back=()=>{if(changed.length&&!window.confirm('Hay cambios sin guardar. ¿Descartarlos?'))return;setSource(null);setDraft({});setMessage('');};
 const save=()=>start(async()=>{
  const changes=changed.flatMap(block=>block.keys.map((key,i)=>({key,value:i===0?draft[block.id]:byKey[key].value,revision:byKey[key].revision})));
  if(changed.some(block=>!draft[block.id].trim())){setMessage('Los bloques no pueden quedar vacíos.');return;}
  try{const result=await saveSiteContent(changes);if(result.error){setMessage(result.error);return;}setValues(current=>current.map(e=>{const change=changes.find(c=>c.key===e.key);return change?{...e,value:change.value,revision:e.revision+1}:e;}));setDraft({});setMessage('Cambios publicados en esta página.');}catch{setMessage('No se pudo guardar. Tus cambios siguen aquí.');}
 });
 if(!source)return <section className="space-y-6"><header><h1 className="text-3xl font-bold">Textos de las páginas</h1><p className="mt-2 text-slate-600">Elige dónde quieres cambiar el contenido. Encontrarás títulos, subtítulos y párrafos reunidos por sección.</p><p className="mt-2"><Link className="underline" href="/admin/products">Editar productos</Link> · <Link className="underline" href="/admin/blog">Crear y editar artículos del blog</Link></p></header><label className="block">Buscar página<input className="mt-2 block w-full rounded-lg border p-3" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Inicio, asesoría, carrito…"/></label><div className="grid gap-4 md:grid-cols-2">{sources.filter(s=>contentLocation(s).title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(s=>{const location=contentLocation(s),pageBlocks=blocks.filter(b=>b.source===s);return <button key={s} className="rounded-2xl border bg-white p-6 text-left hover:border-brand-700" onClick={()=>{setSource(s);setPreview(false);}}><h2 className="text-xl font-bold">{location.title}</h2><p className="mt-1 text-sm text-slate-500">Ubicación: {location.url}</p><p className="mt-3 line-clamp-2 text-sm">{[...new Set(pageBlocks.map(b=>b.section))].slice(0,3).join(' · ')}</p><p className="mt-4 font-semibold text-brand-700">Editar secciones →</p></button>;})}</div></section>;
 const location=contentLocation(source);
 return <section className="space-y-6"><header className="sticky top-0 z-10 rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><button disabled={pending} onClick={back}>← Todas las páginas</button><a href={location.url} target="_blank" rel="noreferrer" className="underline">Abrir página publicada ↗</a></div><h1 className="mt-3 text-2xl font-bold">{location.title}</h1><p className="text-sm text-slate-600">{location.url} · Los cambios se guardan únicamente en esta página.</p><div className="mt-4 flex flex-wrap items-center gap-3"><button aria-pressed={preview} onClick={()=>setPreview(!preview)} className="rounded-full border px-4 py-2">{preview?'Volver a editar':'Vista previa del texto'}</button><button disabled={pending||!changed.length} onClick={save} className="rounded-full bg-brand-700 px-5 py-2 text-white disabled:opacity-50">{pending?'Guardando…':`Publicar ${changed.length} cambios`}</button></div>{message&&<p role="status" className="mt-3">{message}</p>}</header><fieldset disabled={pending} className="space-y-6">{[...new Set(active.map(b=>b.section))].map(section=><section key={section} className="rounded-2xl border bg-white p-5"><h2 className="mb-4 text-lg font-bold">Sección: {section}</h2>{['Título','Subtítulo','Párrafo','Botón o enlace','Otros textos'].map(type=>{const fields=active.filter(b=>b.section===section&&b.type===type);if(!fields.length)return null;return <fieldset key={type} className="mb-5 space-y-4"><legend className="mb-2 text-sm font-semibold uppercase tracking-wide text-brand-700">{type==='Párrafo'?'Párrafos':type}</legend>{fields.map((block,i)=><div key={block.id}>{preview?<div className={type==='Título'?'text-3xl font-bold':type==='Subtítulo'?'text-xl font-semibold':'whitespace-pre-wrap leading-7'}>{draft[block.id]??text(block)}</div>:<label className="block text-sm">{block.label}{fields.length>1?` ${i+1}`:''}<textarea className="mt-2 block w-full rounded-lg border p-3 text-base" rows={type==='Párrafo'?4:2} maxLength={12000} value={draft[block.id]??text(block)} onChange={e=>setDraft({...draft,[block.id]:e.target.value})}/></label>}</div>)}</fieldset>;})}</section>)}</fieldset></section>;
}
