import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.MAI_PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
 await page.goto('http://127.0.0.1:3000/routines');assert.equal(await page.locator('h1').count(),1);await page.locator('#elige-tu-ritual').scrollIntoViewIfNeeded(); await page.waitForFunction(()=>Array.from(document.querySelectorAll('#elige-tu-ritual img')).every(img=>img.complete&&img.naturalWidth>0)); await page.screenshot({path:'/tmp/mai-rituals-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Agregar el kit a mi bolsa ↗',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('mai-cart')||'[]').length===1);let cart=await page.evaluate(()=>JSON.parse(localStorage.getItem('mai-cart')));assert.equal(cart[0].id,'kit-ritual-facial-mai');assert.equal(cart[0].amountInCents,17160000);
 await page.evaluate(()=>localStorage.removeItem('mai-cart'));await page.reload();await page.getByRole('button',{name:'Adaptar este ritual ↗',exact:true}).click();let summary=page.getByRole('complementary',{name:'Resumen de tu ritual'});await summary.getByText('3 de 6 productos elegidos',{exact:true}).waitFor();assert.ok((await summary.innerText()).includes('195.000'));await page.getByRole('radio',{name:'Cuerpo',exact:true}).check();await page.getByRole('button',{name:/^Elegir Jabón Sólido/}).first().click();await summary.getByText('4 de 6 productos elegidos',{exact:true}).waitFor();
 await page.getByLabel('Dale un nombre (opcional)').fill('Mi pausa');const whatsapp=summary.getByRole('link',{name:/Consultar esta selección/});assert.ok(decodeURIComponent(await whatsapp.getAttribute('href')).includes('Mi pausa'));await page.reload();await page.getByRole('button',{name:/03 \/ A TU MANERA/}).click();await summary.getByText('4 de 6 productos elegidos',{exact:true}).waitFor();assert.equal(await page.getByLabel('Dale un nombre (opcional)').inputValue(),'Mi pausa');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/mai-rituals-custom-mobile.png',fullPage:true});await page.getByRole('link',{name:/Ver mi selección/}).click();await summary.getByRole('button',{name:'Agregar mi selección (4) ↗',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('mai-cart')||'[]').length===4);cart=await page.evaluate(()=>JSON.parse(localStorage.getItem('mai-cart')));assert.equal(cart.every(i=>i.quantity===1),true);assert.equal(cart.some(i=>i.id.startsWith('kit-')),false);
 await page.goto('http://127.0.0.1:3000/checkout');await page.getByRole('heading',{name:'Tu cuidado, casi en casa.'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS kit price and SKU, adaptation prices, mixed categories, saved draft, contextual WhatsApp, mobile summary, custom cart and checkout; no orders or payments created.');
}finally{await browser.close();}
