"use client";
import { SiteText, useEditorialData } from "@/components/common/SiteText";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { useCart } from "@/components/features/cart/CartContext";
import { trackAddToCart, trackEvent } from "@/lib/analytics";
import type { Product } from "@/lib/products";
import { baseRituals as originalRituals, canAddSelection, canSelectProduct, selectionTotal } from "@/lib/rituals";
import styles from "./rituals.module.css";
const money = (cents: number) => new Intl.NumberFormat("es-CO", {style:"currency",currency:"COP",maximumFractionDigits:0}).format(cents / 100);
const categories = [{id:"all",label:"Todo"},{id:"facial",label:"Rostro"},{id:"capilar",label:"Cabello"},{id:"corporal",label:"Cuerpo"}];
export default function RoutineBuilderView({ products }: { products: Product[] }) {
  const baseRituals = useEditorialData("rituals", originalRituals);
 const {items,addItem,openCart}=useCart();
 const [mode,setMode]=useState("facial");
 const [chosen,setChosen]=useState<string[]>([]);
 const [category,setCategory]=useState("all");
 const [name,setName]=useState("");
 const [message,setMessage]=useState("");
 const [added,setAdded]=useState(false);
 const lock=useRef(false);
 const result=useRef<HTMLDivElement>(null);
 const custom=mode==="custom";
 const profile=baseRituals.find(p=>p.id===mode) ?? baseRituals[0];
 const catalog=products.filter(p=>p.category!=="kits" && p.active!==false && p.amountInCents>0);
 const selection=(custom?chosen:profile.productIds).map(id=>products.find(p=>p.id===id)).filter((p):p is Product=>Boolean(p));
 const purchase=selection;
 const available=canAddSelection(purchase,items) && (custom ? chosen.length===selection.length : selection.length===profile.productIds.length);
 const total=selectionTotal(purchase);
 const title=custom?(name.trim() || "Mi ritual MAI"):profile.label;
 useEffect(()=>{try{const raw=JSON.parse(sessionStorage.getItem("mai-custom-ritual")||"null");if(raw&&Array.isArray(raw.ids)){setChosen([...new Set<string>(raw.ids.filter((id:unknown)=>typeof id==="string"&&products.some(p=>p.id===id&&p.category!=="kits"&&p.active!==false)))].slice(0,6));setName(typeof raw.name==="string"?raw.name.slice(0,60):"");}}catch{/* An unavailable draft must not block choosing products. */}},[products]); // Revalidate a saved selection against the current catalog.
 function remember(ids:string[],label=name){try{sessionStorage.setItem("mai-custom-ritual",JSON.stringify({ids,name:label}));}catch{}}
 function choose(next:string){setMode(next);setAdded(false);lock.current=false;setMessage("");trackEvent("ritual_path_selected",{ritual_type:next});requestAnimationFrame(()=>result.current?.focus());}
 function customize(){const ids=[...profile.productIds];setChosen(ids);remember(ids);choose("custom");trackEvent("ritual_customize",{base:profile.id});}
 function toggle(product:Product){setAdded(false);lock.current=false;let next:string[];if(chosen.includes(product.id))next=chosen.filter(id=>id!==product.id);else{if(chosen.length>=6){setMessage("Tu selección tiene 6 productos. Quita uno para elegir otro.");return;}next=[...chosen,product.id];}setChosen(next);remember(next);setMessage(chosen.includes(product.id)?`${product.name} retirado de tu selección.`:`${product.name} añadido a tu selección.`);}
 function add(){if(!available||lock.current)return;lock.current=true;purchase.forEach(p=>{addItem({id:p.id,name:p.name,price:p.price,amountInCents:p.amountInCents,image:p.image});trackAddToCart({item_id:p.id,item_name:p.name,price:p.amountInCents/100,quantity:1});});setAdded(true);setMessage("Tu selección está en la bolsa. Puedes revisar las cantidades antes de continuar.");trackEvent("ritual_added_to_cart",{ritual_type:mode,product_count:purchase.length,value:total/100,currency:"COP"});openCart();}
 const whatsapp=`https://wa.me/573246847727?text=${encodeURIComponent(`Hola MAI, quiero orientación sobre ${title}. Mi selección: ${selection.map(p=>p.name).join("; ") || "aún por definir"}. ${purchase.length?`Subtotal de referencia: ${money(total)} COP. `:""}Quiero confirmar disponibilidad y cómo elegir los productos.`)}`;
 return <div className={styles.page}>
  <header className={styles.hero}><div><p className={styles.eyebrow}><SiteText id="b2f4ddf541add7c93750">{"TU RITUAL MAI"}</SiteText></p><h1><SiteText id="57da2412347b90a077a9">{"El cuidado empieza"}</SiteText><br/><SiteText id="68d7eef45213b9c39024">{"por "}</SiteText><em><SiteText id="1c0fb61abfbdf51fa0e6">{"elegirte."}</SiteText></em></h1><p><SiteText id="b9dee116910bb887a6bc">{"Dos rituales para empezar. Una selección que puedes hacer tuya. Elige lo que tiene sentido para tu momento, sin llevarte más de lo que necesitas."}</SiteText></p><a href="#elige-tu-ritual" className={styles.textLink}><SiteText id="9357cbf283999274f088">{"Encuentra tu punto de partida ↓"}</SiteText></a></div><div className={styles.heroNote}><span aria-hidden="true"><SiteText id="f37f09c0c9dacd2e1342">{"01 — 02 — tú"}</SiteText></span><p><SiteText id="67a2d6ddf2edaf51286f">{"Un gesto."}</SiteText><br/><SiteText id="9a8ed7243aeb86ed4e29">{"Un momento."}</SiteText><br/><em><SiteText id="7a57c4cbcf490b25d801">{"Tu manera de cuidarte."}</SiteText></em></p><small><SiteText id="f45b87a4209f85cc4a16">{"Formulaciones botánicas de autor · Elaboradas uno a uno en Colombia"}</SiteText></small></div></header>
  <section id="elige-tu-ritual" className={styles.paths} aria-labelledby="ritual-path-title"><div className={styles.sectionHead}><p className={styles.eyebrow}><SiteText id="f89609db0977720ac885">{"01 / TU PUNTO DE PARTIDA"}</SiteText></p><h2 id="ritual-path-title"><SiteText id="36b0c5bc706d4b5af255">{"¿Por dónde quieres empezar?"}</SiteText></h2><p><SiteText id="64b38368a419358e8cba">{"Elige una base o combina productos a tu manera."}</SiteText></p></div>
  <div className={styles.pathGrid}>{baseRituals.map((p,index)=>{const bundle=products.find(x=>x.id===p.productIds[0]);return <button type="button" key={p.id} aria-pressed={mode===p.id} aria-controls="ritual-selection" onClick={()=>choose(p.id)} className={`${styles.path} ${mode===p.id?styles.active:""}`}><div className={styles.pathImage}>{bundle&&<Image src={bundle.image} alt="" fill sizes="(max-width:700px) 85vw, 30vw" className="object-cover"/>}<span>0{index+1} / {p.label}</span></div><div className={styles.pathText}><h3>{p.title}</h3><p>{p.description}</p><strong>{"Selección de 3 productos · precios individuales"}</strong><span>{mode===p.id?"Estás explorando este ritual ✓":"Explorar ritual ↗"}</span></div></button>;})}
  <button type="button" aria-pressed={custom} aria-controls="ritual-selection" onClick={()=>choose("custom")} className={`${styles.customPath} ${custom?styles.active:""}`}><span className={styles.eyebrow}><SiteText id="4cb5d4210c5776e91bc4">{"03 / A TU MANERA"}</SiteText></span><span className={styles.customMark} aria-hidden="true">+</span><h3><SiteText id="ab5b3e64153e7bfee08c">{"Crea el tuyo."}</SiteText></h3><p><SiteText id="c7e3c7c55724733960e2">{"Rostro, cabello y cuerpo. Agrupa hasta 6 productos en una selección propia, con el precio siempre a la vista."}</SiteText></p><strong><SiteText id="adcccf60694037cec52a">{"Eliges tú · pagas lo que sumas"}</SiteText></strong><span>{custom?"Estás creando tu ritual ✓":"Armar mi selección ↗"}</span></button></div></section>
  <section id="ritual-selection" className={styles.builder} aria-labelledby="selection-title"><div ref={result} tabIndex={-1} className={styles.sectionHead}><p className={styles.eyebrow}>02 / {custom?"HAZLO TUYO":"CONOCE TU RITUAL"}</p><h2 id="selection-title">{custom?"Tu cuidado, a tu manera.":profile.label}</h2><p>{custom?"Puedes comenzar desde cero o adaptar una de las bases. Selecciona una unidad de cada producto; podrás ajustar cantidades en la bolsa.":profile.note}</p></div>
  <div className={styles.builderGrid}><div>
  {!custom?<><ol className={styles.steps}>{profile.productIds.map((id,index)=>{const product=products.find(p=>p.id===id);return <li key={id}><div className={styles.stepImage}>{product?<Image src={product.image} alt={product.name} fill sizes="(max-width:700px) 28vw, 220px" className="object-cover"/>:<span><SiteText id="af416c118f0dff4f886c">{"Por confirmar"}</SiteText></span>}</div><p className={styles.eyebrow}>0{index+1} / {profile.steps[index]}</p>{product?<h3><Link href={`/products/${id}`}>{product.name}</Link></h3>:<p><SiteText id="163a22631fe0386ed54c">{"Producto no disponible"}</SiteText></p>}</li>})}</ol><div className={styles.adapt}><h3><SiteText id="35e4638a9a503cc55e42">{"¿Cambiarías algo?"}</SiteText></h3><p><SiteText id="e20f7b09b3d8a6239e64">{"Usa estos productos como punto de partida y agrega o quita lo que prefieras. Se aplican los precios individuales de cada producto."}</SiteText></p><button type="button" onClick={customize} className={styles.secondary}><SiteText id="38c4d7f07f9d67de49e5">{"Adaptar este ritual ↗"}</SiteText></button></div></>:<><label className={styles.nameField}><SiteText id="90ca3da85071543322e1">{"Dale un nombre (opcional)"}</SiteText><input maxLength={60} value={name} placeholder="Mi pausa de los domingos" onChange={e=>{setName(e.target.value);remember(chosen,e.target.value)}}/><small><SiteText id="2e25d28902769178e218">{"El nombre acompaña tu consulta de orientación; no solicita un empaque especial."}</SiteText></small></label><fieldset className={styles.filters}><legend><SiteText id="fc7543e23ef143837dde">{"Explora por cuidado"}</SiteText></legend>{categories.map(c=><label key={c.id}><input type="radio" name="ritual-category" checked={category===c.id} onChange={()=>setCategory(c.id)}/><span>{c.label}</span></label>)}</fieldset><div className={styles.productGrid}>{catalog.filter(p=>category==="all"||p.category===category).map(p=>{const picked=chosen.includes(p.id);const disabled=!picked&&(!canAddSelection([p],items)||chosen.length>=6);return <article key={p.id} className={picked?styles.picked:styles.product}><div className={styles.productImage}><Image src={p.image} alt="" fill sizes="(max-width:700px) 40vw, 220px" className="object-cover"/></div><h3><Link href={`/products/${p.id}`}>{p.name}</Link></h3><p>{money(p.amountInCents)}<SiteText id="d3cac8d2f5c94df1c523">{" COP"}</SiteText></p><button type="button" aria-pressed={picked} disabled={disabled} aria-label={`${picked?"Quitar":"Elegir"} ${p.name}`} onClick={()=>toggle(p)}>{picked?"Elegido ✓ · quitar":!canSelectProduct(p)?"No disponible":chosen.length>=6?"Selección completa":"Elegir +"}</button></article>})}</div></>}
  </div><aside id="ritual-summary" className={styles.summary} aria-label="Resumen de tu ritual"><p className={styles.eyebrow}><SiteText id="50282fee2b29096250aa">{"TU SELECCIÓN"}</SiteText></p><h3>{title}</h3>{custom?<><p role="status">{selection.length}<SiteText id="ea17e0af334fd63f448f">{" de 6 productos elegidos"}</SiteText></p>{selection.length?<ul>{selection.map(p=><li key={p.id}><span>{p.name}<small>{money(p.amountInCents)}<SiteText id="d3cac8d2f5c94df1c523">{" COP"}</SiteText></small></span><button type="button" aria-label={`Retirar ${p.name} de mi ritual`} onClick={()=>toggle(p)}><SiteText id="397f8d0c5c69f44d3e13">{"×"}</SiteText></button></li>)}</ul>:<p className={styles.empty}><SiteText id="51eab8e46f9f76730c31">{"Tu primer producto puede ser ese que ya conoces o uno que quieres descubrir."}</SiteText></p>}</>:<p>Los productos se agregan como artículos individuales.</p>}
  <div className={styles.total}><span>{"Subtotal de productos"}</span><strong>{purchase.some(p => p.amountInCents <= 0) ? "Precio por confirmar" : purchase.length?`${money(total)} COP`:"Elige tu primer producto"}</strong><small><SiteText id="5fb9cefbd98f59ee2f18">{"Envío y total en el checkout. Pago seguro con Wompi."}</SiteText></small></div><button type="button" className={styles.primary} disabled={!available||added} onClick={add}>{added?"Agregado a tu bolsa ✓":custom?`Agregar mi selección${selection.length?` (${selection.length})`:""} ↗`:"Agregar la selección a mi bolsa ↗"}</button>{added&&<button type="button" className={styles.secondary} onClick={openCart}><SiteText id="0baec2bed750d5becc5e">{"Revisar mi bolsa"}</SiteText></button>}{custom&&<p className={styles.finePrint}><SiteText id="3f817f900becafbc0185">{"Los productos personalizados se agregan como artículos individuales, sin descuento automático. Si ya tienes alguno, se suma una unidad a su cantidad."}</SiteText></p>}{!available&&purchase.length>0&&<p role="status" className={styles.finePrint}><SiteText id="9ca88126f660cd61d471">{"Revisa disponibilidad o cantidades en tu bolsa antes de añadir esta selección."}</SiteText></p>}<p role="status" className={styles.finePrint}>{message}</p><a href={whatsapp} target="_blank" rel="noopener noreferrer" className={styles.textLink}><SiteText id="2b6a40416fc3e7503f47">{"Consultar esta selección por WhatsApp ↗"}</SiteText></a></aside></div></section>
  <section className={styles.help}><div><p className={styles.eyebrow}><SiteText id="ef49b33f84c8c5c0dc21">{"ELEGIR TAMBIÉN ES CUIDARTE"}</SiteText></p><h2><SiteText id="c287be90d8f0b49a3028">{"¿Prefieres comenzar"}</SiteText><br/><SiteText id="cc7c38baebdc02e95b04">{"con una conversación?"}</SiteText></h2><p><SiteText id="1ec217d78f9b68f4aad7">{"Melina puede acompañarte a revisar tus hábitos y elegir un punto de partida. Crear una selección aquí no equivale a una formulación personalizada."}</SiteText></p><Link href="/services" className={styles.textLink}><SiteText id="3bb078692efcf2be7577">{"Conocer las asesorías ↗"}</SiteText></Link></div><div className={styles.faq}>{[["¿Cómo se calcula el precio del ritual?","Sumamos los precios individuales de los productos. No hay descuento automático; verás el subtotal antes de agregarlo."],["¿Puedo combinar rostro, cabello y cuerpo?","Sí. En «Crea el tuyo» puedes elegir hasta 6 productos distintos. La selección no implica que deban mezclarse o usarse todos juntos: sigue las indicaciones de cada producto."],["¿Cómo se confirma mi pedido?","En la bolsa puedes revisar cantidades. El equipo confirma disponibilidad, envío y total antes de pagar con Wompi. El checkout indica si Wompi está habilitado para pagar o únicamente para una simulación sin cobro real."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 {custom&&<a href="#ritual-summary" className={styles.mobileSummary}><span>{selection.length}<SiteText id="b8cda311f58e975d50f5">{" productos · "}</SiteText>{money(total)}<SiteText id="d3cac8d2f5c94df1c523">{" COP"}</SiteText></span><strong><SiteText id="3dfe4a1f8cd9d58ecd47">{"Ver mi selección ↑"}</SiteText></strong></a>}
 </div>;
}
